import type { Metadata } from 'next'
import './globals.css'
import { Montserrat, Asap } from 'next/font/google'
 
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-body',
  display: 'swap',
})
 
const asap = Asap({
  subsets: ['latin'],
  variable: '--font-heading',
  display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${montserrat.variable} ${asap.variable}`}>
            <body className={montserrat.className}>{children}</body>
        </html>
    )
}
